### ISSUE TITLE
Encyclopedia links aren't working

### ISSUE THREAD

**Issue by felhasznalo** [movitto/nethack-encyclopedia#6]
When I click on a link, the same wiki page opens in a new instance.

Example:
Navigate to: encyclopedia -> "b" -> "Buc".
Click on ["item"](http://i.imgur.com/B69KJUG.png) (the link in the first paragraph).
A new "Buc" window opens instead of the "item" wiki page.

Using the latest Google Play version.
(However, this isn't a new bug introduced in the update, it didn't work for me before version 6, 7.)

SM-G900F, Android 5.0

**Comment by movitto** [comment]
Good catch, thanks for this. Seems the base url being used for encyclopedia pages was not valid w/ more recent version of android. Changed the schema to 'file' to comply with recent validations with commit #1d68ab & pushed a new version to google play
