### ISSUE TITLE
unable to scroll game tracker windows in some cases

### ISSUE THREAD

**Issue by felhasznalo** [movitto/nethack-encyclopedia#7]
Can't scroll the windows in the game tracker if they became larger than the screen after they have been created.

Example:
Go to: game tracker -> item info -> plus sign (fits the screen so far) [[1]](http://i.imgur.com/3UoQDJG.png)
Select potions, yellow as apperiance.
The item name text field is now filled, the window doesn't fit the screen, and it is not scrollable. [[2]](http://i.imgur.com/a8fEOJV.png)

**Comment by movitto** [comment]
Awesome, verified and fixed this w/ the latest commit. Pushed it to the android store. Thanks for this!
